import 'package:flutter/painting.dart';

const white = _white;
const grey = _whiteSmoke;
const greyText = _shadyLady;
const black = _black;
const red = _red;
const blue = _blue;
const orange = _tangerine;
const green = _green;
const greyBackground = _crprus;
const darkBlue = _darkBlue;
const darkOrange = _darkOrange;
const darkRed = _darkRed;
const darkGreyText = _darkGrey;
const brightPink = _brightPink;
const darkPink = _darkPink;
const darkGreen = _darkGreen;
const pinkButtonColor = _pinkButtonColor;
const anotherGrayColor = _anotherGrayColor;
const selectedMonthColor = _colorOfChosenMonth;


const _white = Color(0XFFFFFFFF);
const _black = Color(0XFF000000);
const _red = Color(0xFFEE2B00);
const _blue = Color(0xFF009FEE);
const _whiteSmoke = Color(0xFFEFEFEF);
const _shadyLady = Color(0xFF969696);
const _tangerine = Color(0xFFEE8F00);
const _crprus = Color(0xFFF3F4F6);
const _green = Color(0xFF008000);
const _darkGreen = Color(0xFF1A2421);
const _darkBlue = Color(0xFF056EA1);
const _darkOrange = Color(0xFFB86E00);
const _darkRed = Color(0xFFBF2200);
const _darkGrey = Color(0xFF7C7B7B);
const _brightPink = Color(0xFFF6CFC6);
const _darkPink = Color(0xFFe75480);
const _pinkButtonColor = Color(0xFFFEE8E9);
const _anotherGrayColor = Color(0xFF111827);
const _colorOfChosenMonth = Color(0xFF292929);